#!/bin/bash

# This script tests the following functionality:
# 1. Start kelly node
# 2. Configure kelly via http rest api
# 3. Test http api with using both eunit and py.test
# 4. Stop kelly node

echo PWD: ${PWD}

KELLY_BASE="${PWD}/rel/kelly"
KELLY_BIN="${KELLY_BASE}/bin/kelly"
PIPE_DIR="/tmp/${PWD}/rel/kelly/"

echo Start kelly node
$KELLY_BIN start

echo Wait 10 sec for kelly node start
sleep 10

echo Ping node
KELLY_PING_RESULT=$($KELLY_BIN ping | grep pong)
if [[ "" == "$KELLY_PING_RESULT" ]]; then
    exit 1
fi

echo Stub SNMP
echo "k_control_snmp_stub:enable()." | ${KELLY_BASE}/erts-5.10.4/bin/to_erl ${PIPE_DIR}
sleep 1

echo Configure kelly node
./rel/files/http_conf.sh

if [[ "0" == "$?" ]]; then
    echo Configure success
else
    exit 1
fi

echo Start tests
./rebar eunit skip_deps=true
EUNIT_RES=$?
py.test -vv test/*.py
PYTEST_RES=$?

echo Stop node
$KELLY_BIN stop

echo -n Wait 5 sec for kelly node stop...
sleep 5
echo OK

if [[ ${EUNIT_RES} == 0 && ${PYTEST_RES} == 0 ]]; then
    echo Success
    exit 0
else
    echo Failure
    cat ${KELLY_BASE}/log/debug.log
    exit 1
fi
