#!/bin/bash

# This script tests the following functionality:
# 1. Start kelly node
# 2. Configure kelly via http rest api
# 3. Test http api with using both eunit and py.test
# 4. Stop kelly node

echo PWD: $(pwd)

KELLY_BIN='./rel/kelly/bin/kelly'

echo Start kelly node
$KELLY_BIN start

echo Wait 10 sec for kelly node start
sleep 10

echo Ping node
KELLY_PING_RESULT=$($KELLY_BIN ping | grep pong)
if [[ "" == "$KELLY_PING_RESULT" ]]; then
    exit 1
fi

echo Configure kelly node
./rel/files/http_conf.sh

if [[ "0" == "$?" ]]; then
    echo Configure success
else
    exit 1
fi

echo Start tests
./rebar eunit skip_deps=true
EUNIT_RES=$?
py.test -v test/*.py
PYTEST_RES=$?

echo Stop node
$KELLY_BIN stop

echo -n Wait 5 sec for kelly node stop...
sleep 5
echo OK

if [[ ${EUNIT_RES} == 0 && ${PYTEST_RES} == 0 ]]; then
    echo Success
    exit 0
else
    echo Failure
    exit 1
fi
