language: erlang
script: "make simple-test"
otp_release:
  - R15B03
notifications:
  email:
    - d.klionsky@dev.powermemobile.com
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq uuid-dev
services:
  - mongodb
  - rabbitmq
