language: erlang
script: "make simple-test"
otp_release:
  - R16B03-1
notifications:
  email:
    - d.klionsky@dev.powermemobile.com
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq uuid-dev
 - sudo apt-get install -qq python-pytest python-requests
services:
  - mongodb
  - rabbitmq
