{application,k_mb_amqp,
             [{description,"Provides amqp interaction for mailbox application"},
              {vsn,"0.0.1"},
              {registered,[]},
              {applications,[kernel,stdlib,amqp_client,lager]},
              {mod,{k_mb_amqp_app,[]}},
              {env,[]},
              {modules,[k_mb_amqp,k_mb_amqp_app,k_mb_amqp_consumer_srv,
                        k_mb_amqp_funs,k_mb_amqp_fw_srv,k_mb_amqp_pool,
                        k_mb_amqp_sup]}]}.
