#!/bin/bash

#
# Gateways
#
curl -s -D - -X 'POST' 127.0.0.1:8080/gateways -d 'id=804e3d4a-dc38-11e3-90ee-00269e42f7a5&name=SMPPSim2&rps=10000'; echo; echo

curl -s -D - -X 'POST' 127.0.0.1:8080/gateways -d 'id=96a46498-dc38-11e3-8541-00269e42f7a5&name=SMPPSim3&rps=10000'; echo; echo

#
# Connections (SMPPSim2)
#
curl -s -D - -X 'POST' 127.0.0.1:8080/gateways/804e3d4a-dc38-11e3-90ee-00269e42f7a5/connections -d "id=1&host=127.0.0.1&port=8002&bind_type=transmitter&system_id=smppclient1&password=password&system_type=SMPP&addr_ton=1&addr_npi=1&addr_range="; echo; echo

curl -s -D - -X 'POST' 127.0.0.1:8080/gateways/804e3d4a-dc38-11e3-90ee-00269e42f7a5/connections -d "id=2&host=127.0.0.1&port=8002&bind_type=receiver&system_id=smppclient2&password=password&system_type=SMPP&addr_ton=1&addr_npi=1&addr_range="; echo; echo

#
# Connections (SMPPSim3)
#
curl -s -D - -X 'POST' 127.0.0.1:8080/gateways/96a46498-dc38-11e3-8541-00269e42f7a5/connections -d "id=1&host=127.0.0.1&port=8003&bind_type=transmitter&system_id=smppclient1&password=password&system_type=SMPP&addr_ton=1&addr_npi=1&addr_range="; echo; echo

curl -s -D - -X 'POST' 127.0.0.1:8080/gateways/96a46498-dc38-11e3-8541-00269e42f7a5/connections -d "id=2&host=127.0.0.1&port=8003&bind_type=receiver&system_id=smppclient2&password=password&system_type=SMPP&addr_ton=1&addr_npi=1&addr_range="; echo; echo

#
# Providers
#
curl -s -D - -X 'PUT' 127.0.0.1:8080/providers/0a89542c-5270-11e1-bf27-001d0947ec73 -d 'name=SMPPSim%20MTS'; echo; echo

curl -s -D - -X 'POST' 127.0.0.1:8080/providers -d 'id=103fc6bc-dc39-11e3-859e-00269e42f7a5&name=SMPPSim2%20Velcom&description=&gateway_id=804e3d4a-dc38-11e3-90ee-00269e42f7a5&bulk_gateway_id=804e3d4a-dc38-11e3-90ee-00269e42f7a5&receipts_supported=true&sms_add_points=0.0'; echo; echo

curl -s -D - -X 'POST' 127.0.0.1:8080/providers -d 'id=2277349a-dc39-11e3-9202-00269e42f7a5&name=SMPPSim3%20Life&description=&gateway_id=96a46498-dc38-11e3-8541-00269e42f7a5&bulk_gateway_id=96a46498-dc38-11e3-8541-00269e42f7a5&receipts_supported=true&sms_add_points=0.0'; echo; echo


#
# Networks
#
curl -s -D - -X 'PUT' 127.0.0.1:8080/networks/6dd0af45-7cdf-41aa-954b-cc368fe1968e -d 'provider_id=103fc6bc-dc39-11e3-859e-00269e42f7a5&is_home=true&sms_points=1.0&sms_mult_points=1.0'; echo; echo

curl -s -D - -X 'PUT' 127.0.0.1:8080/networks/0456837f-e874-4b05-8e89-95ae20b897d2 -d 'provider_id=0a89542c-5270-11e1-bf27-001d0947ec73&is_home=false&sms_points=2.0&sms_mult_points=1.0'; echo; echo

curl -s -D - -X 'PUT' 127.0.0.1:8080/networks/793e7b47-b248-4c86-a26f-eadfc44f84e2 -d 'provider_id=2277349a-dc39-11e3-9202-00269e42f7a5&is_home=false&sms_points=3.0&sms_mult_points=1.0'; echo; echo
