#!/bin/bash

# SMPPSim
OUTPUT_SMPP_HOST=127.0.0.1
OUTPUT_SMPP_PORT=8001
# SMS Collider
#OUTPUT_SMPP_HOST=127.0.1.1
#OUTPUT_SMPP_PORT=2775

###
# Be aware:
# 1. Customer's `priority' and `rps' settings are disabled, due to http://extranet.powermemobile.com/issues/17465
# 2. Customer's `default_validity' in time format, described in SMPP specification v3.4
###

# To test PUT requests:
# curl --request PUT 'Url' --data 'Body'
# httpc:request(put, {Url, [], "application/x-www-form-urlencoded", Body}, [], []).

#
# Gateways
#
echo -n 'id=7dc235d0-c938-4b66-8f8c-c9037c7eace7&name=SMPPSim&rps=10000' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/gateways; echo

# set gateway's settings
#echo -n 'id=log_smpp_pdus&value=true' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/gateways/7dc235d0-c938-4b66-8f8c-c9037c7eace7/settings; echo


#
# Connections (SMPPSim)
#
echo -n "id=0&host=$OUTPUT_SMPP_HOST&port=$OUTPUT_SMPP_PORT&bind_type=transmitter&system_id=smppclient1&password=password&system_type=SMPP&addr_ton=1&addr_npi=1&addr_range=" | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/gateways/7dc235d0-c938-4b66-8f8c-c9037c7eace7/connections; echo

echo -n "id=1&host=$OUTPUT_SMPP_HOST&port=$OUTPUT_SMPP_PORT&bind_type=receiver&system_id=smppclient2&password=password&system_type=SMPP&addr_ton=1&addr_npi=1&addr_range=" | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/gateways/7dc235d0-c938-4b66-8f8c-c9037c7eace7/connections; echo

#
# Providers
#
echo -n 'id=0a89542c-5270-11e1-bf27-001d0947ec73&name=Provider1&gateway=7dc235d0-c938-4b66-8f8c-c9037c7eace7&bulk_gateway=7dc235d0-c938-4b66-8f8c-c9037c7eace7&receipts_supported=true' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/providers; echo

#
# Networks
#
echo -n 'id=920a009a-5270-11e1-b961-001d0947ec73&name=Network1&country_code=375&numbers_len=12&prefixes=29;33;44;25&provider_id=0a89542c-5270-11e1-bf27-001d0947ec73' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/networks; echo

# Networks to test against SMPPSim DeterministicLifeCycleManager
echo -n 'id=10000000-0000-0000-0000-000000000000&name=Network1&country_code=175&numbers_len=12&prefixes=29;33;44;25&provider_id=0a89542c-5270-11e1-bf27-001d0947ec73' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/networks; echo
echo -n 'id=20000000-0000-0000-0000-000000000000&name=Network2&country_code=275&numbers_len=12&prefixes=29;33;44;25&provider_id=0a89542c-5270-11e1-bf27-001d0947ec73' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/networks; echo
echo -n 'id=30000000-0000-0000-0000-000000000000&name=Network3&country_code=375&numbers_len=12&prefixes=29;33;44;25&provider_id=0a89542c-5270-11e1-bf27-001d0947ec73' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/networks; echo
echo -n 'id=40000000-0000-0000-0000-000000000000&name=Network4&country_code=475&numbers_len=12&prefixes=29;33;44;25&provider_id=0a89542c-5270-11e1-bf27-001d0947ec73' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/networks; echo
echo -n 'id=50000000-0000-0000-0000-000000000000&name=Network5&country_code=575&numbers_len=12&prefixes=29;33;44;25&provider_id=0a89542c-5270-11e1-bf27-001d0947ec73' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/networks; echo
echo -n 'id=60000000-0000-0000-0000-000000000000&name=Network6&country_code=675&numbers_len=12&prefixes=29;33;44;25&provider_id=0a89542c-5270-11e1-bf27-001d0947ec73' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/networks; echo

#
# Customers
#

#
# NowSMS

# postpaid
echo -n 'customer_uuid=132109c8-ae67-11e2-bc5a-00269e42f7a5&customer_id=nowsms&name=nowsms&originators=375296660001,1,1&networks=920a009a-5270-11e1-b961-001d0947ec73&receipts_allowed=true&default_validity=000003000000000R&max_validity=259200&default_provider_id=0a89542c-5270-11e1-bf27-001d0947ec73&default_originator=375296660001,1,1&pay_type=postpaid&state=1' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers; echo

# NowSMS users
echo -n 'id=user&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/132109c8-ae67-11e2-bc5a-00269e42f7a5/users; echo


#
# Kannel

# postpaid customer
echo -n 'customer_uuid=feda5822-5271-11e1-bd27-001d0947ec73&customer_id=fun-postpaid&name=funnel-postpaid&originators=375296660001,1,1&networks=920a009a-5270-11e1-b961-001d0947ec73&receipts_allowed=true&default_validity=000003000000000R&max_validity=259200&default_provider_id=0a89542c-5270-11e1-bf27-001d0947ec73&default_originator=375296660001,1,1&pay_type=postpaid&state=1' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers; echo

# Kannel users
echo -n 'id=user&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/feda5822-5271-11e1-bd27-001d0947ec73/users; echo
echo -n 'id=user2&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/feda5822-5271-11e1-bd27-001d0947ec73/users; echo
echo -n 'id=user3&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/feda5822-5271-11e1-bd27-001d0947ec73/users; echo
echo -n 'id=user4&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/feda5822-5271-11e1-bd27-001d0947ec73/users; echo
echo -n 'id=user5&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/feda5822-5271-11e1-bd27-001d0947ec73/users; echo

# prepaid customer
echo -n 'customer_uuid=6bd667ae-1793-11e2-95fe-00269e42f7a5&customer_id=fun-prepaid&name=funnel-prepaid&originators=375296660002,1,1&networks=920a009a-5270-11e1-b961-001d0947ec73&receipts_allowed=true&default_validity=000003000000000R&max_validity=259200&default_provider_id=0a89542c-5270-11e1-bf27-001d0947ec73&default_originator=375296660002,1,1&pay_type=prepaid&state=1' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers; echo

# Kannel's users
echo -n 'id=user&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/6bd667ae-1793-11e2-95fe-00269e42f7a5/users; echo
echo -n 'id=user2&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/6bd667ae-1793-11e2-95fe-00269e42f7a5/users; echo
echo -n 'id=user3&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/6bd667ae-1793-11e2-95fe-00269e42f7a5/users; echo
echo -n 'id=user4&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/6bd667ae-1793-11e2-95fe-00269e42f7a5/users; echo
echo -n 'id=user5&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/6bd667ae-1793-11e2-95fe-00269e42f7a5/users; echo

#
# OneAPI

# postpaid customer
echo -n 'customer_uuid=a3ddc34a-1793-11e2-9602-00269e42f7a5&customer_id=oneapi-postpaid&name=oneapi-postpaid&originators=375296660003,1,1&networks=920a009a-5270-11e1-b961-001d0947ec73&receipts_allowed=true&default_validity=000003000000000R&max_validity=259200&default_provider_id=0a89542c-5270-11e1-bf27-001d0947ec73&default_originator=375296660003,1,1&pay_type=postpaid&state=1' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers; echo

echo -n 'id=user&password=password&connection_types=oneapi' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/a3ddc34a-1793-11e2-9602-00269e42f7a5/users; echo

# prepaid customer
echo -n 'customer_uuid=16f87550-1794-11e2-ade6-00269e42f7a5&customer_id=oneapi-prepaid&name=oneapi-prepaid&originators=375296660004,1,1&networks=920a009a-5270-11e1-b961-001d0947ec73&receipts_allowed=true&default_validity=000003000000000R&max_validity=259200&default_provider_id=0a89542c-5270-11e1-bf27-001d0947ec73&default_originator=375296660004,1,1&pay_type=prepaid&state=1' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers; echo

echo -n 'id=user&password=password&connection_types=oneapi' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/16f87550-1794-11e2-ade6-00269e42f7a5/users; echo

#
# Soap
#

# postpaid customer
echo -n 'customer_uuid=c173786e-63ce-11e2-8740-001d0947ec73&customer_id=soap-postpaid&name=soap-postpaid&originators=999,6,0&networks=920a009a-5270-11e1-b961-001d0947ec73&receipts_allowed=true&default_validity=000003000000000R&max_validity=259200&default_provider_id=0a89542c-5270-11e1-bf27-001d0947ec73&default_originator=999,6,0&pay_type=postpaid&state=1' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers; echo

echo -n 'id=user&password=password&connection_types=soap' |
lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/c173786e-63ce-11e2-8740-001d0947ec73/users; echo

#
# MM-client
#

# postpaid customer
echo -n 'customer_uuid=8032706a-b4ec-11e3-b3d7-00269e42f7a5&customer_id=1&name=mm-postpaid&originators=375296660003,1,1&networks=920a009a-5270-11e1-b961-001d0947ec73&receipts_allowed=true&default_validity=000003000000000R&max_validity=259200&default_provider_id=0a89542c-5270-11e1-bf27-001d0947ec73&default_originator=375296660004,1,1&pay_type=postpaid&state=1' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers; echo

echo -n 'id=user&password=password&connection_types=mm' |
lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/8032706a-b4ec-11e3-b3d7-00269e42f7a5/users; echo

#
# smppload
#

# postpaid customer
echo -n 'customer_uuid=493b3678-9dc8-11e2-8cce-00269e42f7a5&customer_id=&name=smppload-postpaid&originators=375296660002,1,1&networks=920a009a-5270-11e1-b961-001d0947ec73;10000000-0000-0000-0000-000000000000;20000000-0000-0000-0000-000000000000;30000000-0000-0000-0000-000000000000;40000000-0000-0000-0000-000000000000;50000000-0000-0000-0000-000000000000;60000000-0000-0000-0000-000000000000&receipts_allowed=true&default_validity=000003000000000R&max_validity=259200&default_provider_id=0a89542c-5270-11e1-bf27-001d0947ec73&default_originator=375296660002,1,1&pay_type=postpaid&state=1' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers; echo

# users
echo -n 'id=user&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/493b3678-9dc8-11e2-8cce-00269e42f7a5/users; echo
echo -n 'id=user2&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/493b3678-9dc8-11e2-8cce-00269e42f7a5/users; echo
echo -n 'id=user3&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/493b3678-9dc8-11e2-8cce-00269e42f7a5/users; echo
echo -n 'id=user4&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/493b3678-9dc8-11e2-8cce-00269e42f7a5/users; echo
echo -n 'id=user5&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/493b3678-9dc8-11e2-8cce-00269e42f7a5/users; echo

# prepaid customer
echo -n 'customer_uuid=50cec0fa-ea33-11e2-8cb1-00269e42f7a5&customer_id=prepaid&name=smppload-prepaid&originators=375296660002,1,1&networks=920a009a-5270-11e1-b961-001d0947ec73;10000000-0000-0000-0000-000000000000;20000000-0000-0000-0000-000000000000;30000000-0000-0000-0000-000000000000;40000000-0000-0000-0000-000000000000;50000000-0000-0000-0000-000000000000;60000000-0000-0000-0000-000000000000&receipts_allowed=true&default_validity=000003000000000R&max_validity=259200&default_provider_id=0a89542c-5270-11e1-bf27-001d0947ec73&default_originator=375296660002,1,1&pay_type=prepaid&state=1' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers; echo

# users
echo -n 'id=user&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/50cec0fa-ea33-11e2-8cb1-00269e42f7a5/users; echo
echo -n 'id=user2&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/50cec0fa-ea33-11e2-8cb1-00269e42f7a5/users; echo
echo -n 'id=user3&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/50cec0fa-ea33-11e2-8cb1-00269e42f7a5/users; echo
echo -n 'id=user4&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/50cec0fa-ea33-11e2-8cb1-00269e42f7a5/users; echo
echo -n 'id=user5&password=password&connection_types=transmitter;receiver;transceiver' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/customers/50cec0fa-ea33-11e2-8cb1-00269e42f7a5/users; echo


#
# Addr2Cust
#

echo -n 'msisdn=375296660001,1,1&customer=feda5822-5271-11e1-bd27-001d0947ec73&user=user' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/addr2cust; echo
echo -n 'msisdn=375296660002,1,1&customer=6bd667ae-1793-11e2-95fe-00269e42f7a5&user=undefined' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/addr2cust; echo
# oneapi postpaid customer
echo -n 'msisdn=375296660003,1,1&customer=a3ddc34a-1793-11e2-9602-00269e42f7a5&user=undefined' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/addr2cust; echo
# oneapi prepaid customer
echo -n 'msisdn=375296660004,1,1&customer=16f87550-1794-11e2-ade6-00269e42f7a5&user=undefined' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/addr2cust; echo
# soap postpaid customer
echo -n 'msisdn=375296660005,1,1&customer=c173786e-63ce-11e2-8740-001d0947ec73&user=undefined' | lwp-request -UsSe -m 'POST' 127.0.0.1:8080/addr2cust; echo
